use DIO_ecommerce;

#Inserindo dados na tabela Product

insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (1, 14, 22, 'Jewelry', 'Exclusive solution-oriented paradigm', 728, 3, 529.7);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (2, 9, 43, 'Beauty', 'Cross-group client-driven Graphical User Interface', 2681, 4, 75.54);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (3, 21, 45, 'Toys', 'Expanded uniform contingency', 1253, 2, 493.47);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (4, 29, 11, 'Beauty', 'Object-based impactful support', 669, 4, 443.17);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (5, 18, 59, 'Electronics', 'Multi-lateral eco-centric database', 922, 1, 233.39);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (6, 20, 14, 'Games', 'Optional system-worthy infrastructure', 2908, 7, 135.05);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (7, 1, 92, 'Industrial', 'Managed value-added support', 823, 2, 15.88);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (8, 7, 112, 'Grocery', 'Multi-layered context-sensitive concept', 2909, 2, 420.06);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (9, 14, 94, 'Toys', 'Multi-channelled zero administration installation', 2968, 8, 787.89);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (10, 18, 68, 'Music', 'Phased composite budgetary management', 1253, 9, 615.61);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (11, 24, 104, 'Shoes', 'Customer-focused global access', 1587, 7, 203.23);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (12, 11, 75, 'Clothing', 'Upgradable solution-oriented application', 1664, 2, 30.19);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (13, 23, 82, 'Garden', 'Organized 3rd generation model', 976, 8, 326.46);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (14, 21, 8, 'Clothing', 'Synergized 4th generation migration', 777, 3, 113.92);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (15, 27, 92, 'Health', 'Down-sized responsive framework', 671, 1, 104.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (16, 20, 3, 'Beauty', 'Multi-tiered upward-trending focus group', 60, 6, 58.89);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (17, 22, 102, 'Books', 'Fundamental attitude-oriented function', 2922, 6, 157.65);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (18, 6, 95, 'Music', 'Organized dedicated moratorium', 1128, 4, 120.17);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (19, 26, 109, 'Clothing', 'Front-line discrete portal', 1087, 6, 347.5);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (20, 20, 103, 'Music', 'Seamless real-time capability', 239, 4, 53.29);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (21, 20, 53, 'Music', 'Monitored intermediate superstructure', 1757, 1, 210.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (22, 8, 48, 'Jewelry', 'Re-engineered explicit knowledge base', 1539, 5, 381.99);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (23, 20, 116, 'Outdoors', 'Advanced 24 hour core', 462, 4, 146.68);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (24, 16, 77, 'Beauty', 'Reactive modular function', 2315, 4, 54.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (25, 4, 7, 'Home', 'De-engineered exuding strategy', 2219, 3, 39.36);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (26, 27, 63, 'Movies', 'Down-sized asymmetric data-warehouse', 139, 4, 445.93);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (27, 16, 76, 'Health', 'Up-sized static algorithm', 302, 7, 705.56);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (28, 10, 114, 'Toys', 'Devolved content-based approach', 2510, 5, 116.66);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (29, 22, 62, 'Kids', 'Assimilated tangible flexibility', 469, 3, 181.13);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (30, 17, 99, 'Books', 'Intuitive multi-state success', 1727, 8, 544.7);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (31, 24, 36, 'Shoes', 'Operative transitional array', 44, 7, 198.6);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (32, 30, 116, 'Books', 'Quality-focused asymmetric extranet', 2332, 10, 536.86);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (33, 9, 80, 'Toys', 'Right-sized coherent circuit', 2477, 8, 457.97);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (34, 10, 65, 'Computers', 'Visionary multi-tasking extranet', 2760, 10, 462.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (35, 4, 85, 'Automotive', 'Re-engineered disintermediate internet solution', 1843, 3, 316.48);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (36, 7, 8, 'Jewelry', 'Optional stable open system', 870, 7, 262.44);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (37, 7, 66, 'Computers', 'Robust directional open architecture', 1669, 5, 79.66);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (38, 26, 39, 'Toys', 'Multi-lateral upward-trending matrices', 2087, 2, 401.96);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (39, 5, 102, 'Home', 'Profound 3rd generation application', 1730, 10, 789.07);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (40, 11, 62, 'Industrial', 'Secured bi-directional analyzer', 710, 9, 204.31);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (41, 28, 63, 'Shoes', 'Switchable coherent budgetary management', 532, 9, 212.28);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (42, 16, 45, 'Tools', 'Vision-oriented dedicated standardization', 2751, 7, 147.22);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (43, 19, 32, 'Garden', 'Configurable user-facing hardware', 415, 4, 197.2);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (44, 14, 50, 'Outdoors', 'Enterprise-wide tertiary open system', 1823, 8, 56.94);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (45, 10, 93, 'Computers', 'Persistent radical challenge', 1934, 6, 180.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (46, 20, 88, 'Grocery', 'Function-based static structure', 1818, 5, 169.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (47, 11, 56, 'Sports', 'Persevering methodical extranet', 460, 6, 871.86);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (48, 3, 14, 'Home', 'Enterprise-wide bifurcated projection', 1281, 3, 18.06);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (49, 11, 43, 'Beauty', 'Re-contextualized 24/7 portal', 131, 7, 127.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (50, 7, 113, 'Movies', 'Proactive 4th generation circuit', 2798, 4, 194.18);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (51, 28, 9, 'Automotive', 'Fundamental bifurcated challenge', 46, 2, 1135.8);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (52, 3, 30, 'Movies', 'Robust mission-critical implementation', 1710, 6, 283.46);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (53, 26, 11, 'Games', 'Proactive stable task-force', 31, 4, 560.38);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (54, 16, 69, 'Baby', 'Synergistic solution-oriented superstructure', 2357, 9, 106.01);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (55, 1, 86, 'Garden', 'Reduced web-enabled paradigm', 2273, 1, 173.06);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (56, 9, 119, 'Jewelry', 'Team-oriented object-oriented local area network', 1970, 7, 66.04);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (57, 7, 58, 'Beauty', 'Operative real-time leverage', 1826, 3, 15.29);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (58, 20, 98, 'Kids', 'Persistent non-volatile model', 2895, 6, 276.71);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (59, 8, 41, 'Beauty', 'Open-source exuding Graphic Interface', 2575, 7, 196.24);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (60, 1, 58, 'Movies', 'Exclusive content-based core', 152, 8, 5.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (61, 26, 30, 'Baby', 'Networked content-based help-desk', 71, 1, 408.44);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (62, 18, 51, 'Grocery', 'Business-focused client-server Graphical User Interface', 1045, 4, 121.13);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (63, 11, 92, 'Computers', 'Virtual 3rd generation middleware', 689, 2, 499.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (64, 17, 97, 'Beauty', 'Mandatory regional hardware', 153, 4, 559.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (65, 13, 114, 'Computers', 'Organic fresh-thinking strategy', 1717, 6, 425.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (66, 13, 105, 'Movies', 'Focused multimedia strategy', 2183, 9, 408.34);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (67, 3, 121, 'Outdoors', 'Polarised clear-thinking product', 2414, 5, 300.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (68, 29, 42, 'Automotive', 'Optimized user-facing alliance', 2310, 5, 330.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (69, 7, 110, 'Home', 'Synchronised uniform open architecture', 660, 3, 553.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (70, 8, 97, 'Health', 'Total optimizing internet solution', 2348, 2, 469.47);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (71, 10, 92, 'Grocery', 'Organic national hub', 538, 2, 278.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (72, 17, 105, 'Books', 'Realigned client-server access', 515, 8, 387.32);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (73, 22, 45, 'Books', 'Virtual local methodology', 873, 2, 554.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (74, 14, 69, 'Industrial', 'Open-architected bifurcated implementation', 1778, 9, 281.91);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (75, 3, 102, 'Home', 'Streamlined next generation encryption', 2877, 9, 146.28);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (76, 27, 87, 'Jewelry', 'Adaptive multi-tasking service-desk', 2273, 8, 233.25);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (77, 12, 62, 'Outdoors', 'Fully-configurable bottom-line attitude', 1912, 10, 4.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (78, 3, 46, 'Grocery', 'Re-engineered 4th generation solution', 2527, 6, 438.54);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (79, 2, 77, 'Games', 'Proactive non-volatile open architecture', 2479, 9, 294.15);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (80, 16, 78, 'Electronics', 'Self-enabling 3rd generation model', 2277, 10, 9.21);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (81, 8, 75, 'Baby', 'Managed client-server policy', 981, 7, 626.45);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (82, 27, 68, 'Beauty', 'Extended coherent open system', 370, 4, 211.98);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (83, 30, 104, 'Jewelry', 'Customer-focused intermediate matrices', 1002, 6, 572.66);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (84, 27, 88, 'Computers', 'Open-source tertiary challenge', 1672, 7, 346.54);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (85, 11, 59, 'Clothing', 'Organized 3rd generation standardization', 2464, 7, 794.05);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (86, 30, 91, 'Tools', 'Public-key multi-state secured line', 1206, 1, 135.33);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (87, 9, 30, 'Toys', 'Realigned content-based core', 2681, 1, 943.62);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (88, 8, 5, 'Movies', 'Self-enabling 24 hour frame', 2529, 2, 136.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (89, 29, 61, 'Garden', 'Advanced 6th generation data-warehouse', 885, 6, 397.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (90, 16, 21, 'Health', 'Persevering zero defect projection', 108, 9, 379.0);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (91, 28, 5, 'Shoes', 'Stand-alone object-oriented methodology', 282, 9, 62.74);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (92, 4, 71, 'Toys', 'Virtual fault-tolerant moratorium', 1180, 9, 20.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (93, 20, 55, 'Sports', 'Integrated homogeneous core', 196, 3, 596.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (94, 5, 3, 'Outdoors', 'Profound upward-trending encoding', 1289, 8, 377.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (95, 25, 97, 'Sports', 'Multi-channelled eco-centric software', 935, 8, 577.15);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (96, 7, 114, 'Automotive', 'Robust static parallelism', 1842, 5, 70.9);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (97, 9, 79, 'Automotive', 'Focused asynchronous conglomeration', 277, 6, 429.26);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (98, 9, 33, 'Music', 'Object-based full-range leverage', 2967, 5, 172.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (99, 12, 11, 'Tools', 'Universal impactful installation', 2327, 2, 12.18);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (100, 3, 91, 'Industrial', 'Decentralized neutral migration', 2544, 1, 276.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (101, 6, 70, 'Beauty', 'Fully-configurable bandwidth-monitored complexity', 1334, 3, 232.7);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (102, 7, 83, 'Music', 'Object-based upward-trending throughput', 113, 7, 61.48);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (103, 9, 86, 'Books', 'Front-line multi-tasking architecture', 1710, 2, 468.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (104, 22, 29, 'Baby', 'Multi-lateral local migration', 1674, 1, 248.17);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (105, 23, 34, 'Beauty', 'Phased global emulation', 2273, 6, 78.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (106, 1, 8, 'Games', 'Centralized homogeneous frame', 2677, 8, 193.38);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (107, 17, 13, 'Health', 'Multi-tiered executive attitude', 2529, 2, 457.75);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (108, 11, 83, 'Movies', 'Assimilated background utilisation', 2088, 10, 227.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (109, 5, 22, 'Electronics', 'Ameliorated 4th generation paradigm', 2935, 1, 280.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (110, 7, 38, 'Books', 'Polarised logistical hardware', 1950, 2, 140.06);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (111, 9, 44, 'Home', 'Universal optimizing artificial intelligence', 1050, 8, 235.27);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (112, 27, 58, 'Shoes', 'Inverse asymmetric superstructure', 1314, 9, 205.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (113, 8, 71, 'Electronics', 'Centralized homogeneous structure', 1634, 5, 6.27);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (114, 29, 22, 'Toys', 'Visionary heuristic open architecture', 843, 5, 567.66);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (115, 6, 102, 'Garden', 'Self-enabling client-server moratorium', 1950, 7, 122.59);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (116, 17, 43, 'Sports', 'Implemented empowering product', 1986, 3, 193.48);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (117, 10, 73, 'Games', 'Networked clear-thinking array', 1456, 9, 1053.62);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (118, 19, 31, 'Movies', 'Re-contextualized upward-trending leverage', 669, 7, 483.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (119, 9, 107, 'Games', 'Pre-emptive optimal success', 1566, 3, 308.66);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (120, 12, 58, 'Home', 'Synergized value-added implementation', 2874, 1, 177.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (121, 29, 114, 'Movies', 'Re-engineered modular throughput', 2726, 5, 994.13);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (122, 23, 22, 'Clothing', 'Reactive attitude-oriented internet solution', 1577, 10, 506.65);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (123, 20, 24, 'Kids', 'Pre-emptive background workforce', 29, 8, 355.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (124, 17, 8, 'Computers', 'Reduced background Graphical User Interface', 19, 5, 422.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (125, 6, 54, 'Garden', 'Enterprise-wide global portal', 668, 10, 423.22);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (126, 28, 99, 'Automotive', 'Organized zero defect capability', 1756, 5, 18.46);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (127, 17, 51, 'Jewelry', 'Optimized holistic knowledge base', 2396, 3, 646.41);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (128, 6, 105, 'Electronics', 'Profound asymmetric service-desk', 2948, 10, 539.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (129, 15, 83, 'Home', 'Robust 24 hour Graphical User Interface', 996, 10, 91.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (130, 12, 12, 'Home', 'Future-proofed next generation attitude', 171, 8, 194.0);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (131, 28, 39, 'Jewelry', 'Polarised dedicated Graphic Interface', 2643, 2, 465.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (132, 21, 45, 'Home', 'Down-sized interactive knowledge user', 577, 5, 381.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (133, 26, 34, 'Computers', 'Proactive bi-directional interface', 606, 2, 635.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (134, 26, 1, 'Kids', 'Seamless didactic extranet', 1968, 2, 224.31);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (135, 26, 21, 'Home', 'Synchronised multi-state concept', 2687, 8, 129.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (136, 23, 84, 'Kids', 'Reactive neutral secured line', 2581, 8, 497.85);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (137, 5, 68, 'Games', 'Digitized clear-thinking standardization', 1521, 3, 798.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (138, 12, 77, 'Electronics', 'Ameliorated attitude-oriented internet solution', 2724, 1, 393.22);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (139, 28, 72, 'Industrial', 'Profound solution-oriented projection', 2208, 8, 397.81);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (140, 29, 84, 'Garden', 'Reduced local interface', 450, 7, 132.12);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (141, 2, 54, 'Books', 'Synergistic zero defect data-warehouse', 1175, 2, 290.91);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (142, 26, 101, 'Tools', 'Function-based fresh-thinking orchestration', 2193, 2, 122.43);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (143, 17, 80, 'Games', 'Open-source explicit productivity', 1052, 10, 691.69);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (144, 14, 9, 'Sports', 'Operative reciprocal contingency', 2354, 8, 229.41);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (145, 28, 65, 'Grocery', 'Managed object-oriented Graphical User Interface', 952, 1, 503.36);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (146, 10, 111, 'Electronics', 'Ergonomic real-time monitoring', 1240, 1, 387.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (147, 30, 14, 'Health', 'Ergonomic system-worthy adapter', 1186, 6, 432.26);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (148, 24, 16, 'Grocery', 'Fully-configurable homogeneous project', 2466, 9, 84.07);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (149, 17, 28, 'Jewelry', 'Organized global hierarchy', 2347, 2, 750.24);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (150, 16, 107, 'Books', 'User-centric static forecast', 21, 3, 518.81);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (151, 25, 8, 'Outdoors', 'Ergonomic tertiary utilisation', 1305, 10, 684.3);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (152, 2, 87, 'Movies', 'Intuitive hybrid time-frame', 605, 2, 134.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (153, 6, 92, 'Clothing', 'Open-architected bi-directional info-mediaries', 1886, 2, 121.32);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (154, 1, 96, 'Baby', 'Diverse empowering paradigm', 501, 7, 963.92);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (155, 22, 48, 'Garden', 'Triple-buffered even-keeled database', 980, 6, 214.59);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (156, 15, 113, 'Sports', 'Open-architected asymmetric application', 2261, 1, 253.21);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (157, 28, 112, 'Electronics', 'Down-sized responsive success', 1773, 9, 54.86);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (158, 18, 74, 'Baby', 'Public-key heuristic frame', 2417, 3, 598.36);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (159, 20, 7, 'Electronics', 'Devolved analyzing frame', 1342, 6, 77.62);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (160, 11, 6, 'Clothing', 'Re-contextualized 24/7 methodology', 396, 4, 186.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (161, 9, 110, 'Grocery', 'Advanced holistic Graphical User Interface', 148, 9, 227.33);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (162, 26, 43, 'Grocery', 'Phased cohesive software', 1509, 3, 234.02);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (163, 1, 15, 'Electronics', 'Synergized national Graphic Interface', 2394, 2, 398.04);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (164, 23, 60, 'Baby', 'Extended dedicated matrix', 1094, 9, 130.75);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (165, 16, 36, 'Grocery', 'Secured fresh-thinking migration', 2033, 2, 546.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (166, 15, 119, 'Home', 'Advanced holistic website', 2540, 9, 876.94);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (167, 12, 17, 'Clothing', 'Implemented logistical ability', 764, 6, 399.47);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (168, 9, 87, 'Grocery', 'Cloned well-modulated focus group', 1023, 1, 856.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (169, 29, 50, 'Automotive', 'Ameliorated fresh-thinking portal', 495, 1, 23.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (170, 11, 70, 'Clothing', 'Universal asymmetric model', 339, 8, 154.35);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (171, 15, 27, 'Books', 'Enterprise-wide background array', 1799, 3, 161.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (172, 2, 73, 'Games', 'Innovative content-based extranet', 2859, 6, 626.01);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (173, 17, 117, 'Health', 'Front-line zero defect complexity', 940, 4, 380.97);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (174, 9, 119, 'Beauty', 'Configurable object-oriented matrix', 319, 6, 301.83);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (175, 23, 19, 'Automotive', 'Organized solution-oriented neural-net', 2349, 10, 540.99);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (176, 27, 65, 'Games', 'Optional neutral project', 992, 7, 33.23);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (177, 24, 118, 'Toys', 'Organized incremental migration', 648, 5, 207.73);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (178, 28, 30, 'Electronics', 'Open-architected systemic functionalities', 603, 1, 74.23);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (179, 18, 59, 'Health', 'Business-focused multi-tasking pricing structure', 1365, 3, 37.57);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (180, 8, 107, 'Electronics', 'Reduced disintermediate framework', 2287, 10, 344.89);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (181, 13, 7, 'Computers', 'Compatible bifurcated software', 1265, 4, 549.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (182, 20, 33, 'Books', 'Fully-configurable tangible success', 1284, 5, 394.08);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (183, 28, 4, 'Beauty', 'Multi-layered heuristic data-warehouse', 592, 6, 306.83);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (184, 12, 114, 'Computers', 'Multi-layered coherent knowledge base', 848, 3, 304.22);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (185, 2, 35, 'Movies', 'Cross-platform 4th generation parallelism', 1965, 4, 210.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (186, 13, 2, 'Garden', 'Inverse context-sensitive monitoring', 1394, 10, 25.2);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (187, 6, 82, 'Industrial', 'Enhanced upward-trending circuit', 2622, 3, 679.11);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (188, 2, 11, 'Kids', 'Synergistic multi-tasking infrastructure', 609, 5, 68.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (189, 15, 100, 'Grocery', 'Fundamental coherent hardware', 737, 2, 43.48);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (190, 1, 90, 'Computers', 'Devolved 3rd generation standardization', 1413, 5, 709.2);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (191, 11, 1, 'Tools', 'Extended didactic open system', 541, 9, 167.04);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (192, 14, 15, 'Sports', 'Fully-configurable next generation website', 1044, 6, 342.66);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (193, 30, 28, 'Clothing', 'Reduced asynchronous solution', 754, 4, 347.29);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (194, 24, 54, 'Outdoors', 'Adaptive real-time superstructure', 2445, 7, 72.82);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (195, 22, 75, 'Automotive', 'Triple-buffered composite hierarchy', 710, 2, 440.39);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (196, 20, 27, 'Beauty', 'Right-sized incremental standardization', 2785, 4, 194.18);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (197, 3, 83, 'Automotive', 'Managed incremental Graphical User Interface', 2692, 2, 244.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (198, 12, 68, 'Games', 'Versatile neutral framework', 984, 9, 695.9);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (199, 19, 51, 'Electronics', 'Quality-focused 6th generation pricing structure', 110, 8, 36.46);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (200, 26, 80, 'Books', 'Programmable asymmetric forecast', 749, 5, 575.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (201, 5, 90, 'Games', 'Fully-configurable multi-state benchmark', 860, 7, 913.2);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (202, 23, 10, 'Books', 'Fundamental 4th generation model', 242, 5, 250.34);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (203, 15, 121, 'Music', 'Reduced regional ability', 508, 6, 95.29);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (204, 25, 23, 'Baby', 'Sharable methodical approach', 1311, 1, 430.68);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (205, 1, 104, 'Jewelry', 'Programmable regional artificial intelligence', 2883, 3, 283.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (206, 5, 62, 'Industrial', 'Balanced fault-tolerant info-mediaries', 2368, 10, 198.54);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (207, 26, 52, 'Home', 'Face to face methodical local area network', 2561, 4, 113.85);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (208, 7, 55, 'Beauty', 'Exclusive discrete project', 2140, 7, 358.41);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (209, 30, 68, 'Computers', 'Visionary bi-directional data-warehouse', 713, 3, 119.13);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (210, 28, 2, 'Sports', 'Expanded interactive core', 2091, 9, 25.24);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (211, 16, 68, 'Games', 'Multi-layered static workforce', 542, 5, 127.71);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (212, 4, 118, 'Music', 'Expanded modular hardware', 2238, 7, 186.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (213, 5, 115, 'Home', 'Realigned zero tolerance contingency', 2527, 5, 286.62);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (214, 28, 9, 'Games', 'Reduced intangible firmware', 2401, 3, 435.98);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (215, 2, 12, 'Grocery', 'Managed background task-force', 57, 2, 683.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (216, 16, 110, 'Beauty', 'Function-based intermediate challenge', 2936, 2, 628.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (217, 16, 19, 'Baby', 'Seamless content-based toolset', 1108, 4, 788.17);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (218, 11, 36, 'Baby', 'Programmable heuristic portal', 524, 4, 575.04);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (219, 8, 58, 'Outdoors', 'Implemented 24/7 matrices', 754, 4, 543.21);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (220, 15, 71, 'Garden', 'Automated context-sensitive matrices', 2692, 5, 751.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (221, 7, 60, 'Music', 'Multi-channelled exuding function', 330, 8, 336.57);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (222, 28, 5, 'Garden', 'De-engineered impactful adapter', 585, 2, 611.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (223, 1, 116, 'Garden', 'Devolved context-sensitive archive', 379, 1, 605.97);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (224, 20, 41, 'Music', 'Re-contextualized zero defect strategy', 2383, 4, 249.39);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (225, 30, 91, 'Home', 'Future-proofed holistic standardization', 852, 3, 187.83);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (226, 11, 121, 'Industrial', 'Multi-tiered leading edge implementation', 1752, 5, 260.81);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (227, 24, 64, 'Kids', 'Profit-focused motivating infrastructure', 617, 8, 587.19);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (228, 12, 92, 'Games', 'Team-oriented high-level policy', 1423, 4, 8.44);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (229, 4, 26, 'Music', 'Intuitive bottom-line application', 1739, 5, 40.91);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (230, 24, 79, 'Computers', 'Triple-buffered heuristic complexity', 2624, 4, 591.6);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (231, 8, 76, 'Kids', 'Digitized heuristic artificial intelligence', 55, 2, 2.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (232, 7, 95, 'Jewelry', 'Grass-roots background installation', 2697, 2, 299.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (233, 4, 113, 'Toys', 'Reactive disintermediate migration', 1876, 5, 368.98);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (234, 3, 20, 'Home', 'Visionary background hub', 2852, 6, 19.76);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (235, 25, 73, 'Beauty', 'Fundamental dedicated leverage', 1270, 6, 276.32);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (236, 2, 79, 'Shoes', 'Multi-channelled multi-state circuit', 2181, 8, 189.92);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (237, 17, 50, 'Baby', 'Team-oriented uniform implementation', 1853, 10, 546.52);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (238, 5, 34, 'Jewelry', 'Re-engineered systemic pricing structure', 237, 2, 229.59);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (239, 22, 46, 'Garden', 'De-engineered next generation matrix', 1339, 2, 16.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (240, 22, 119, 'Automotive', 'Switchable 5th generation infrastructure', 548, 7, 655.54);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (241, 23, 19, 'Garden', 'Innovative responsive encryption', 2052, 9, 53.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (242, 22, 38, 'Music', 'Enhanced scalable software', 2460, 1, 603.73);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (243, 10, 2, 'Jewelry', 'Self-enabling empowering attitude', 1904, 1, 346.75);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (244, 22, 60, 'Games', 'Stand-alone methodical synergy', 1068, 9, 615.21);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (245, 2, 41, 'Grocery', 'Organized static structure', 591, 8, 101.17);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (246, 7, 49, 'Music', 'Reverse-engineered upward-trending functionalities', 58, 6, 195.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (247, 28, 114, 'Toys', 'Digitized client-server artificial intelligence', 1338, 2, 514.19);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (248, 8, 85, 'Movies', 'Innovative demand-driven approach', 1179, 10, 114.05);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (249, 21, 30, 'Jewelry', 'Front-line fault-tolerant portal', 2864, 9, 68.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (250, 13, 9, 'Computers', 'Customizable explicit productivity', 259, 8, 24.18);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (251, 7, 75, 'Baby', 'Monitored regional parallelism', 1416, 7, 78.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (252, 8, 49, 'Games', 'Phased asymmetric encoding', 2382, 4, 600.55);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (253, 28, 9, 'Health', 'Reverse-engineered even-keeled contingency', 1134, 4, 170.65);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (254, 5, 105, 'Music', 'Upgradable modular initiative', 2590, 10, 93.19);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (255, 10, 114, 'Clothing', 'Ergonomic value-added paradigm', 800, 4, 267.91);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (256, 3, 86, 'Toys', 'Customer-focused neutral strategy', 832, 7, 309.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (257, 25, 119, 'Jewelry', 'Persistent intermediate contingency', 2609, 9, 18.27);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (258, 7, 20, 'Beauty', 'Multi-lateral bi-directional moderator', 598, 4, 87.99);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (259, 17, 84, 'Garden', 'Optimized stable time-frame', 1188, 2, 603.38);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (260, 15, 21, 'Grocery', 'Realigned object-oriented utilisation', 2987, 8, 393.19);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (261, 13, 82, 'Tools', 'Cloned foreground approach', 1382, 5, 111.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (262, 25, 104, 'Outdoors', 'Assimilated 5th generation attitude', 802, 9, 820.45);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (263, 2, 63, 'Shoes', 'Horizontal regional knowledge user', 2179, 10, 499.05);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (264, 5, 14, 'Tools', 'Monitored foreground groupware', 1229, 5, 398.85);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (265, 5, 73, 'Electronics', 'Focused even-keeled application', 492, 3, 171.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (266, 29, 79, 'Beauty', 'Configurable upward-trending middleware', 1846, 10, 220.43);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (267, 2, 81, 'Industrial', 'Realigned non-volatile encryption', 1208, 7, 289.91);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (268, 18, 58, 'Electronics', 'Intuitive optimal hierarchy', 705, 6, 21.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (269, 15, 109, 'Toys', 'Balanced even-keeled synergy', 537, 10, 154.68);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (270, 26, 89, 'Books', 'Organic next generation flexibility', 626, 9, 857.96);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (271, 25, 27, 'Music', 'Optimized dynamic alliance', 2418, 1, 265.53);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (272, 4, 29, 'Music', 'Triple-buffered didactic contingency', 625, 1, 517.98);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (273, 20, 87, 'Outdoors', 'Pre-emptive modular complexity', 194, 2, 326.83);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (274, 17, 99, 'Automotive', 'Cross-platform static synergy', 856, 2, 8.12);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (275, 17, 53, 'Tools', 'Implemented fault-tolerant knowledge base', 702, 4, 316.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (276, 13, 86, 'Automotive', 'Innovative explicit portal', 2275, 7, 639.9);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (277, 18, 94, 'Movies', 'De-engineered high-level ability', 24, 3, 588.63);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (278, 20, 45, 'Toys', 'Configurable discrete time-frame', 1698, 7, 71.62);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (279, 5, 88, 'Automotive', 'Centralized fresh-thinking conglomeration', 1810, 2, 187.68);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (280, 14, 24, 'Electronics', 'Decentralized next generation array', 2154, 2, 186.91);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (281, 22, 2, 'Outdoors', 'Devolved directional approach', 141, 9, 179.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (282, 22, 87, 'Grocery', 'Down-sized human-resource challenge', 2389, 5, 149.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (283, 28, 111, 'Home', 'Assimilated high-level ability', 1557, 8, 404.96);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (284, 28, 98, 'Toys', 'Face to face impactful leverage', 810, 1, 70.33);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (285, 15, 14, 'Clothing', 'Seamless holistic hardware', 1909, 8, 442.26);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (286, 12, 59, 'Clothing', 'Exclusive full-range core', 2235, 10, 333.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (287, 18, 10, 'Music', 'Integrated grid-enabled secured line', 778, 5, 110.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (288, 26, 24, 'Tools', 'Horizontal attitude-oriented matrix', 2410, 3, 483.01);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (289, 23, 73, 'Books', 'Multi-layered leading edge concept', 1144, 6, 19.65);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (290, 24, 104, 'Automotive', 'Cross-platform reciprocal database', 1696, 5, 292.99);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (291, 28, 55, 'Computers', 'Organic solution-oriented challenge', 164, 2, 346.78);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (292, 14, 104, 'Electronics', 'Phased incremental instruction set', 853, 5, 209.02);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (293, 26, 110, 'Industrial', 'Cross-group scalable extranet', 1764, 2, 395.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (294, 8, 65, 'Industrial', 'Re-engineered grid-enabled throughput', 1022, 8, 67.31);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (295, 24, 20, 'Health', 'Phased real-time flexibility', 126, 9, 405.83);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (296, 12, 121, 'Health', 'Grass-roots homogeneous paradigm', 1696, 10, 118.38);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (297, 13, 113, 'Automotive', 'Realigned asymmetric hardware', 58, 7, 215.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (298, 5, 55, 'Health', 'Profit-focused system-worthy hierarchy', 1860, 7, 746.73);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (299, 28, 105, 'Outdoors', 'Triple-buffered composite attitude', 162, 6, 359.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (300, 4, 12, 'Grocery', 'Seamless homogeneous core', 2176, 10, 322.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (301, 1, 103, 'Baby', 'Expanded homogeneous help-desk', 12, 7, 70.46);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (302, 24, 94, 'Outdoors', 'Face to face fault-tolerant system engine', 2365, 6, 437.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (303, 27, 72, 'Tools', 'Expanded solution-oriented protocol', 662, 9, 352.23);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (304, 22, 3, 'Garden', 'Polarised foreground help-desk', 1397, 6, 171.35);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (305, 11, 43, 'Shoes', 'Fundamental hybrid adapter', 742, 2, 293.2);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (306, 18, 101, 'Kids', 'Virtual intermediate customer loyalty', 1368, 2, 25.83);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (307, 9, 43, 'Home', 'Customer-focused human-resource toolset', 2427, 4, 734.71);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (308, 11, 113, 'Shoes', 'Diverse bandwidth-monitored middleware', 1264, 5, 2.69);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (309, 29, 91, 'Baby', 'Triple-buffered heuristic alliance', 858, 6, 1.75);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (310, 20, 11, 'Baby', 'Cloned 6th generation concept', 2973, 5, 82.45);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (311, 30, 62, 'Electronics', 'Reactive real-time secured line', 1535, 1, 748.15);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (312, 22, 60, 'Outdoors', 'Configurable system-worthy contingency', 1, 3, 22.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (313, 11, 74, 'Outdoors', 'Versatile maximized knowledge base', 2418, 7, 83.69);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (314, 14, 97, 'Automotive', 'Front-line interactive attitude', 757, 9, 988.68);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (315, 24, 24, 'Movies', 'Synergized fresh-thinking definition', 872, 8, 84.39);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (316, 20, 50, 'Kids', 'Expanded neutral hub', 1013, 1, 237.29);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (317, 6, 7, 'Kids', 'Profound composite middleware', 2830, 5, 220.98);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (318, 30, 50, 'Beauty', 'Customer-focused 3rd generation customer loyalty', 196, 6, 79.52);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (319, 17, 104, 'Grocery', 'Team-oriented next generation policy', 926, 7, 147.59);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (320, 24, 88, 'Grocery', 'Ergonomic secondary architecture', 1150, 4, 293.34);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (321, 15, 101, 'Health', 'Automated national product', 724, 8, 52.49);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (322, 25, 90, 'Toys', 'Profit-focused bi-directional artificial intelligence', 1877, 1, 64.25);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (323, 27, 43, 'Clothing', 'Assimilated value-added encoding', 2513, 4, 145.36);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (324, 12, 5, 'Automotive', 'Reduced responsive attitude', 1670, 4, 136.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (325, 1, 80, 'Toys', 'Integrated encompassing definition', 2053, 10, 181.25);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (326, 11, 122, 'Clothing', 'Multi-lateral asymmetric initiative', 1009, 5, 739.55);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (327, 8, 47, 'Beauty', 'Fundamental upward-trending info-mediaries', 2130, 10, 988.63);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (328, 25, 114, 'Games', 'Digitized 24 hour Graphic Interface', 2814, 9, 189.61);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (329, 4, 117, 'Beauty', 'Proactive reciprocal alliance', 2633, 10, 108.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (330, 5, 103, 'Movies', 'Expanded mobile product', 2391, 5, 166.52);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (331, 17, 85, 'Beauty', 'Persistent holistic solution', 2878, 5, 33.44);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (332, 21, 87, 'Baby', 'Intuitive leading edge attitude', 2123, 4, 163.12);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (333, 14, 57, 'Grocery', 'Total fault-tolerant array', 1492, 6, 325.35);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (334, 26, 24, 'Automotive', 'Synchronised local budgetary management', 509, 9, 16.75);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (335, 10, 60, 'Clothing', 'Fully-configurable foreground hub', 2210, 4, 117.96);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (336, 25, 118, 'Outdoors', 'Multi-tiered encompassing parallelism', 2156, 2, 214.65);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (337, 28, 116, 'Books', 'Future-proofed intermediate middleware', 836, 4, 907.59);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (338, 20, 101, 'Music', 'Organized dedicated website', 2335, 8, 363.01);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (339, 23, 116, 'Automotive', 'Robust high-level approach', 2679, 3, 605.32);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (340, 1, 69, 'Beauty', 'Down-sized grid-enabled strategy', 1304, 7, 71.72);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (341, 22, 95, 'Shoes', 'Optional stable methodology', 991, 2, 188.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (342, 2, 89, 'Games', 'Persevering value-added adapter', 1969, 4, 130.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (343, 25, 111, 'Electronics', 'Upgradable context-sensitive neural-net', 1479, 10, 11.97);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (344, 18, 103, 'Movies', 'Streamlined mission-critical customer loyalty', 922, 8, 251.52);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (345, 16, 4, 'Shoes', 'Vision-oriented scalable functionalities', 1110, 4, 714.17);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (346, 9, 47, 'Grocery', 'Enhanced radical application', 2229, 3, 202.22);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (347, 19, 23, 'Books', 'Open-architected methodical Graphical User Interface', 1893, 10, 435.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (348, 14, 101, 'Baby', 'Sharable intangible conglomeration', 217, 9, 316.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (349, 28, 50, 'Electronics', 'Persevering content-based time-frame', 231, 10, 742.33);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (350, 6, 51, 'Tools', 'Programmable holistic open system', 1665, 7, 634.5);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (351, 23, 103, 'Grocery', 'Automated bandwidth-monitored focus group', 2300, 5, 635.18);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (352, 23, 109, 'Home', 'Centralized non-volatile matrix', 1380, 1, 424.55);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (353, 22, 80, 'Music', 'Team-oriented empowering implementation', 1794, 4, 384.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (354, 24, 79, 'Music', 'Balanced reciprocal time-frame', 350, 2, 256.57);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (355, 12, 114, 'Health', 'Enterprise-wide discrete flexibility', 1621, 6, 41.54);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (356, 11, 30, 'Sports', 'De-engineered actuating projection', 504, 4, 112.7);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (357, 5, 36, 'Automotive', 'Innovative context-sensitive knowledge base', 1726, 5, 213.34);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (358, 18, 35, 'Automotive', 'Multi-lateral solution-oriented collaboration', 1321, 6, 580.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (359, 3, 112, 'Health', 'Decentralized leading edge orchestration', 2872, 3, 488.86);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (360, 23, 49, 'Home', 'Down-sized 24/7 challenge', 2690, 9, 80.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (361, 20, 63, 'Industrial', 'Multi-channelled optimal leverage', 54, 10, 856.56);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (362, 14, 57, 'Jewelry', 'Versatile client-driven open system', 1271, 6, 236.24);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (363, 25, 97, 'Tools', 'Compatible heuristic leverage', 1518, 2, 462.56);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (364, 14, 73, 'Clothing', 'Fully-configurable incremental workforce', 1468, 2, 127.07);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (365, 20, 120, 'Beauty', 'De-engineered dynamic process improvement', 1744, 4, 67.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (366, 7, 38, 'Shoes', 'De-engineered optimizing initiative', 2339, 3, 151.11);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (367, 21, 63, 'Jewelry', 'Ameliorated solution-oriented concept', 30, 8, 358.71);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (368, 17, 121, 'Garden', 'Organized cohesive encoding', 1160, 3, 422.56);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (369, 25, 14, 'Shoes', 'Quality-focused global open architecture', 1643, 9, 146.96);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (370, 1, 120, 'Toys', 'Cross-platform global support', 334, 1, 323.12);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (371, 7, 25, 'Kids', 'Visionary context-sensitive customer loyalty', 2958, 2, 88.49);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (372, 3, 107, 'Movies', 'Integrated modular orchestration', 2625, 6, 453.5);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (373, 18, 41, 'Garden', 'Vision-oriented explicit migration', 1682, 5, 387.92);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (374, 16, 108, 'Music', 'Face to face zero administration matrices', 854, 10, 766.84);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (375, 19, 53, 'Shoes', 'Organized clear-thinking project', 974, 9, 225.09);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (376, 13, 59, 'Toys', 'Sharable intangible time-frame', 1327, 6, 138.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (377, 27, 111, 'Garden', 'Reactive context-sensitive parallelism', 813, 2, 93.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (378, 2, 33, 'Clothing', 'Total local pricing structure', 2443, 8, 310.03);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (379, 3, 66, 'Beauty', 'Inverse explicit encoding', 952, 1, 201.44);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (380, 9, 16, 'Beauty', 'Face to face solution-oriented implementation', 2453, 9, 52.48);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (381, 2, 44, 'Toys', 'Centralized context-sensitive neural-net', 2942, 7, 102.13);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (382, 23, 88, 'Tools', 'Multi-lateral global matrices', 1022, 5, 115.56);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (383, 30, 101, 'Outdoors', 'Proactive object-oriented synergy', 659, 9, 402.5);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (384, 8, 72, 'Beauty', 'Team-oriented stable internet solution', 2465, 1, 901.89);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (385, 26, 77, 'Electronics', 'Open-source client-server encryption', 1811, 5, 266.89);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (386, 30, 77, 'Beauty', 'Balanced fault-tolerant database', 2510, 3, 550.7);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (387, 27, 19, 'Home', 'Advanced non-volatile moratorium', 1969, 10, 285.67);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (388, 1, 71, 'Movies', 'Fully-configurable zero tolerance orchestration', 1095, 6, 791.35);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (389, 10, 8, 'Jewelry', 'Monitored object-oriented encoding', 2633, 2, 343.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (390, 23, 108, 'Toys', 'Organic client-server initiative', 1235, 2, 349.43);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (391, 13, 68, 'Grocery', 'Quality-focused multimedia groupware', 1495, 7, 416.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (392, 21, 34, 'Outdoors', 'Visionary bandwidth-monitored definition', 2612, 2, 158.55);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (393, 14, 34, 'Jewelry', 'Optional tangible frame', 2708, 6, 210.26);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (394, 4, 62, 'Games', 'Diverse actuating parallelism', 2691, 7, 39.24);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (395, 22, 84, 'Computers', 'Cloned non-volatile groupware', 2682, 6, 502.96);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (396, 10, 25, 'Sports', 'Re-contextualized composite productivity', 2363, 4, 497.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (397, 4, 75, 'Sports', 'Cross-group fresh-thinking function', 2869, 10, 334.41);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (398, 2, 63, 'Automotive', 'Fully-configurable asymmetric implementation', 696, 8, 64.01);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (399, 18, 5, 'Clothing', 'Upgradable foreground website', 1277, 8, 376.99);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (400, 20, 7, 'Kids', 'Vision-oriented 24 hour strategy', 251, 2, 136.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (401, 9, 63, 'Music', 'Fundamental explicit process improvement', 1380, 3, 477.79);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (402, 7, 121, 'Garden', 'Total 3rd generation framework', 1133, 6, 116.38);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (403, 1, 116, 'Automotive', 'Versatile executive core', 1129, 5, 266.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (404, 24, 59, 'Clothing', 'Digitized discrete algorithm', 2432, 9, 23.15);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (405, 11, 40, 'Industrial', 'Proactive attitude-oriented open architecture', 2475, 7, 16.78);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (406, 8, 100, 'Automotive', 'Reactive well-modulated infrastructure', 1970, 8, 10.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (407, 16, 68, 'Grocery', 'Organic client-server solution', 426, 2, 849.48);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (408, 26, 121, 'Books', 'Assimilated context-sensitive access', 2066, 5, 486.15);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (409, 16, 44, 'Computers', 'Diverse intermediate data-warehouse', 1233, 3, 29.02);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (410, 22, 69, 'Games', 'Multi-channelled bottom-line open system', 1271, 9, 211.24);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (411, 26, 33, 'Shoes', 'Customer-focused content-based synergy', 1042, 4, 351.48);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (412, 13, 8, 'Industrial', 'Profit-focused local protocol', 1394, 7, 85.11);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (413, 14, 14, 'Books', 'Managed methodical Graphical User Interface', 1795, 9, 16.29);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (414, 12, 36, 'Tools', 'Reverse-engineered value-added support', 1001, 7, 405.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (415, 11, 107, 'Industrial', 'De-engineered non-volatile interface', 1692, 6, 146.47);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (416, 21, 108, 'Home', 'Multi-layered motivating application', 1094, 3, 398.08);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (417, 18, 7, 'Shoes', 'Polarised hybrid emulation', 1808, 10, 278.97);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (418, 9, 82, 'Kids', 'Networked transitional artificial intelligence', 1487, 3, 248.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (419, 21, 22, 'Computers', 'Upgradable motivating analyzer', 1975, 4, 328.93);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (420, 29, 99, 'Movies', 'Stand-alone needs-based policy', 2993, 10, 5.96);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (421, 10, 110, 'Home', 'Proactive encompassing knowledge user', 1381, 7, 23.3);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (422, 13, 20, 'Kids', 'Innovative fault-tolerant system engine', 976, 7, 190.3);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (423, 6, 34, 'Tools', 'Adaptive value-added infrastructure', 2594, 8, 89.22);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (424, 1, 43, 'Grocery', 'Devolved background policy', 1280, 1, 489.61);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (425, 10, 96, 'Home', 'Quality-focused disintermediate time-frame', 719, 3, 420.6);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (426, 4, 15, 'Movies', 'Assimilated eco-centric hub', 763, 2, 525.36);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (427, 16, 57, 'Toys', 'Universal uniform groupware', 2506, 1, 110.13);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (428, 8, 70, 'Outdoors', 'Function-based disintermediate instruction set', 57, 1, 14.29);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (429, 16, 106, 'Industrial', 'Balanced executive function', 587, 5, 358.63);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (430, 3, 67, 'Music', 'Configurable hybrid matrices', 2207, 3, 339.57);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (431, 27, 77, 'Sports', 'Total 5th generation attitude', 701, 4, 517.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (432, 6, 86, 'Electronics', 'Enhanced didactic analyzer', 2876, 5, 73.03);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (433, 17, 100, 'Outdoors', 'Front-line leading edge synergy', 1024, 7, 110.24);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (434, 27, 111, 'Electronics', 'Distributed zero defect flexibility', 1362, 4, 1475.0);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (435, 4, 58, 'Grocery', 'De-engineered systematic utilisation', 1417, 2, 129.04);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (436, 3, 85, 'Shoes', 'Synergized exuding ability', 2093, 5, 889.13);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (437, 19, 35, 'Baby', 'Ergonomic national info-mediaries', 1062, 2, 834.21);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (438, 6, 113, 'Toys', 'Decentralized asymmetric orchestration', 1808, 7, 703.85);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (439, 9, 50, 'Outdoors', 'Extended maximized productivity', 576, 5, 116.42);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (440, 23, 62, 'Toys', 'Ergonomic global monitoring', 143, 9, 88.22);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (441, 18, 54, 'Beauty', 'Implemented actuating array', 198, 9, 34.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (442, 11, 119, 'Music', 'Profit-focused homogeneous service-desk', 1273, 4, 269.92);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (443, 25, 68, 'Garden', 'Automated reciprocal methodology', 2079, 7, 483.43);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (444, 25, 16, 'Outdoors', 'Innovative logistical database', 902, 1, 354.47);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (445, 6, 22, 'Health', 'Profound interactive hierarchy', 1203, 6, 671.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (446, 22, 52, 'Beauty', 'Multi-channelled responsive circuit', 565, 8, 284.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (447, 9, 107, 'Computers', 'Secured motivating hardware', 1048, 10, 127.51);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (448, 3, 107, 'Sports', 'Up-sized content-based superstructure', 1692, 2, 12.38);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (449, 28, 71, 'Clothing', 'Networked analyzing paradigm', 2093, 1, 213.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (450, 11, 37, 'Jewelry', 'Synergized didactic definition', 337, 2, 199.61);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (451, 30, 92, 'Toys', 'Managed coherent time-frame', 2917, 8, 7.61);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (452, 8, 91, 'Kids', 'Cloned value-added local area network', 2782, 9, 378.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (453, 16, 69, 'Home', 'Synchronised grid-enabled Graphical User Interface', 2023, 8, 155.68);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (454, 30, 110, 'Industrial', 'User-friendly content-based moratorium', 643, 4, 257.5);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (455, 30, 20, 'Movies', 'Ergonomic encompassing methodology', 321, 2, 508.65);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (456, 6, 118, 'Games', 'Profound neutral intranet', 2335, 5, 558.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (457, 15, 5, 'Games', 'Compatible needs-based pricing structure', 911, 8, 909.76);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (458, 7, 65, 'Outdoors', 'Implemented value-added parallelism', 1058, 9, 226.45);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (459, 16, 104, 'Industrial', 'Right-sized intermediate architecture', 2235, 4, 76.68);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (460, 24, 57, 'Shoes', 'Multi-lateral content-based access', 1340, 9, 124.31);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (461, 12, 118, 'Automotive', 'Advanced demand-driven policy', 84, 3, 93.27);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (462, 4, 28, 'Home', 'Visionary client-server benchmark', 1684, 7, 94.89);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (463, 30, 42, 'Electronics', 'Digitized radical customer loyalty', 2177, 10, 730.6);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (464, 7, 42, 'Movies', 'Optional heuristic intranet', 1263, 7, 555.12);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (465, 24, 44, 'Health', 'Reverse-engineered attitude-oriented open system', 2157, 10, 467.37);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (466, 3, 53, 'Home', 'Enterprise-wide tertiary monitoring', 1323, 2, 37.01);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (467, 24, 111, 'Shoes', 'Function-based tangible intranet', 201, 5, 1090.1);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (468, 4, 50, 'Home', 'Secured uniform flexibility', 2640, 4, 399.87);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (469, 20, 38, 'Computers', 'Visionary 4th generation groupware', 2001, 2, 122.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (470, 15, 16, 'Outdoors', 'Advanced human-resource functionalities', 2980, 10, 217.77);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (471, 26, 82, 'Electronics', 'Exclusive exuding groupware', 2554, 1, 487.11);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (472, 20, 49, 'Garden', 'Integrated local productivity', 1415, 7, 29.19);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (473, 29, 79, 'Grocery', 'Open-architected web-enabled instruction set', 2807, 8, 595.2);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (474, 16, 98, 'Garden', 'Upgradable multimedia customer loyalty', 636, 9, 18.9);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (475, 15, 72, 'Clothing', 'Networked contextually-based knowledge base', 1614, 7, 282.95);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (476, 12, 81, 'Shoes', 'Diverse regional strategy', 1607, 3, 297.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (477, 29, 55, 'Health', 'Diverse scalable firmware', 2770, 4, 340.81);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (478, 26, 99, 'Clothing', 'Polarised bottom-line complexity', 2392, 8, 110.82);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (479, 6, 100, 'Beauty', 'Team-oriented content-based website', 2558, 3, 234.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (480, 10, 109, 'Outdoors', 'Sharable fault-tolerant focus group', 734, 8, 596.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (481, 14, 102, 'Sports', 'Multi-lateral systematic capability', 759, 1, 76.07);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (482, 1, 2, 'Outdoors', 'Front-line attitude-oriented policy', 1934, 4, 389.73);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (483, 30, 86, 'Toys', 'Open-architected zero tolerance monitoring', 550, 5, 1474.14);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (484, 8, 39, 'Sports', 'Multi-tiered interactive workforce', 1451, 2, 176.02);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (485, 8, 61, 'Health', 'Organic responsive website', 2053, 3, 264.55);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (486, 21, 78, 'Baby', 'Implemented directional implementation', 2131, 5, 143.4);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (487, 5, 89, 'Games', 'Synergistic context-sensitive product', 214, 8, 260.58);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (488, 9, 9, 'Electronics', 'Reactive didactic conglomeration', 1252, 8, 753.41);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (489, 13, 17, 'Games', 'Enterprise-wide full-range portal', 1908, 5, 556.55);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (490, 4, 97, 'Industrial', 'Persistent systemic internet solution', 595, 4, 339.51);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (491, 24, 122, 'Jewelry', 'Profound even-keeled portal', 2126, 7, 188.19);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (492, 12, 115, 'Toys', 'Networked 4th generation core', 2402, 9, 104.51);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (493, 16, 51, 'Music', 'Versatile bi-directional info-mediaries', 2238, 5, 178.94);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (494, 29, 119, 'Garden', 'Optional human-resource capability', 2215, 4, 260.21);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (495, 23, 91, 'Computers', 'Reduced fault-tolerant Graphic Interface', 1407, 10, 115.9);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (496, 1, 120, 'Automotive', 'Focused background capacity', 1369, 2, 437.69);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (497, 2, 30, 'Tools', 'Expanded eco-centric array', 2639, 8, 567.16);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (498, 24, 114, 'Garden', 'Advanced system-worthy service-desk', 1200, 7, 708.63);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (499, 18, 88, 'Kids', 'Exclusive high-level flexibility', 343, 7, 5.64);
insert into Products (idProduct, idInventory, id3party, category, Description, Size, Weight, Price) values (500, 30, 85, 'Industrial', 'Extended contextually-based framework', 1011, 3, 89.46);
